language: python
dist: xenial
python:
  - '3.6'
  - '3.7'
  - "3.8"
install:
  - pip install setuptools pip wheel --upgrade
  - pip install -r requirements.txt
  - pip install -r doc-source/requirements.txt
script:
  - echo "skipping tests"
before_deploy:
  - ./make_manpage.sh
  - ls
deploy:
  provider: pypi
  user: DomDF
  on:
    tags: true
    python: '3.6'
  distributions: sdist bdist_wheel
  skip_existing: true
  password:
    secure: niA3eF/QMLKJqMMbc3OsgLpn8PvqJXzZog//vOqZVZ1vAKcbTnjE/ATuxjRjnX9znedEPhtzZvxb7rUqqNhmRsQ9+TbZ9yWEbM2eY1XZr33VbvFUuIVmcjpF956Fs5wFHIig237cVWC/hryIgAV3k+rOqoDksoVCdViQuzKJo92vT9UqyIuR+8YLyR8+xaVzZ4V2w3JfgegUUa/UtBUylt3+xSnPFCWgR23os5W1lMhn/ACsQXX5iIeUna39MIok+RVrmvSNDRTUTiTNJ2lxJwZG5EIpdhqp1T+DWzxIFQsiY0Hs/+8HtQOFTQVlQvLFzw2hoJvud5Dpw4v0pqO46djv2aRz/34FCTy1Ee3xAv9RP4uiyTpxI6DNJ9jY2vr0pysBkJaelvTNdENVhUqIohpR8d64qiMXYuGTzm9LAPSIZPKxaHjh1WnzEjYmM3dKDKIvgSVoF2qgRPuR2vWApJvLjKTsmVv3RNjGo2URHFjyXC1VtGrwU5yCJw53RQHpx0wj/bkhz0Bb7fYy172degPctcCnmy8+gHE2x83csQJwNRRZ1yb/CKKfJzq1+QlANVZmqTlYj1nPODBXsgedkNqNZzwt181DFqy7u/mLCo4ygQdPNwOMYA6oObZIOfrINPKGQpPcs+Y1jpFgNJeblaEFEqO3vJUotKXE5gm3hbw=
